export interface DTCData {
  code: string;
  title: string;
  description: string;
  symptoms: string[];
  causes: string[];
  severity: "Low" | "Medium" | "High" | "Critical";
}

export const TOP_DTC_CODES: DTCData[] = [
  { code: "P0420", title: "Catalyst System Efficiency Below Threshold (Bank 1)", description: "The ECM detects that the catalytic converter is not functioning efficiently, meaning emissions are exceeding permissible levels.", symptoms: ["Check Engine Light ON", "Decreased fuel economy", "Lack of engine power", "Rotten egg smell from exhaust"], causes: ["Failed catalytic converter", "Faulty oxygen (O2) sensor", "Exhaust leak", "Engine misfire", "Leaking fuel injector"], severity: "Medium" },
  { code: "P0300", title: "Random/Multiple Cylinder Misfire Detected", description: "The ECM has detected a misfire occurring randomly or across multiple cylinders.", symptoms: ["Check Engine Light flashing", "Rough idle", "Engine hesitation", "Poor fuel economy", "Hard starting"], causes: ["Worn spark plugs", "Faulty ignition coils", "Vacuum leak", "Low fuel pressure", "Clogged fuel injectors", "EGR system fault"], severity: "High" },
  { code: "P0171", title: "System Too Lean (Bank 1)", description: "The engine is running 'lean', meaning there is too much air and not enough fuel in the air/fuel mixture.", symptoms: ["Check Engine Light ON", "Rough idle", "Engine stalling", "Lack of power on acceleration"], causes: ["Vacuum leak", "Faulty Mass Air Flow (MAF) sensor", "Low fuel pressure", "Clogged fuel injectors", "Faulty PCV valve"], severity: "Medium" },
  { code: "P0455", title: "Evaporative Emission System Leak (Gross Leak)", description: "The EVAP system has detected a large leak, allowing fuel vapors to escape into the atmosphere.", symptoms: ["Check Engine Light ON", "Noticeable fuel smell", "Slight drop in fuel economy"], causes: ["Missing or loose gas cap", "Cracked EVAP hose", "Faulty purge valve", "Faulty vent valve", "Damaged fuel tank filler neck"], severity: "Low" },
  { code: "P0113", title: "Intake Air Temperature Sensor 1 Circuit High", description: "The ECM detects a voltage signal from the Intake Air Temperature (IAT) sensor that indicates the air is excessively cold.", symptoms: ["Check Engine Light ON", "Hard starting in cold weather", "Poor engine performance", "Decreased fuel efficiency"], causes: ["Unplugged IAT sensor", "Broken wiring to the IAT sensor", "Failed IAT sensor", "Failed MAF sensor"], severity: "Medium" },
  { code: "P0401", title: "Exhaust Gas Recirculation (EGR) Flow Insufficient", description: "The EGR system is not flowing enough exhaust gases back into the intake manifold.", symptoms: ["Check Engine Light ON", "Engine pinging or knocking on acceleration", "Failed emissions test"], causes: ["Clogged EGR valve or passages", "Faulty DPFE sensor", "Damaged vacuum lines", "Faulty EGR solenoid"], severity: "Medium" },
  { code: "P0135", title: "O2 Sensor Heater Circuit (Bank 1 Sensor 1)", description: "The ECM has detected a malfunction in the heater circuit of the upstream oxygen sensor.", symptoms: ["Check Engine Light ON", "Poor fuel economy during engine warmup", "Rough idle on cold start"], causes: ["Blown O2 sensor heater fuse", "Broken heater wire in the sensor", "Corroded connector", "Failed O2 sensor"], severity: "Low" },
  { code: "P0340", title: "Camshaft Position Sensor 'A' Circuit", description: "The ECM is not receiving a signal from the camshaft position sensor.", symptoms: ["Check Engine Light ON", "Engine crank but no start", "Engine stalling", "Loss of power", "Misfires"], causes: ["Failed camshaft position sensor", "Wiring issue", "Broken timing belt/chain", "Faulty ECM"], severity: "Critical" },
  { code: "P0430", title: "Catalyst System Efficiency Below Threshold (Bank 2)", description: "The ECM detects that Bank 2's catalytic converter efficiency is below normal operating limits.", symptoms: ["Check Engine Light ON", "Sluggish engine performance", "Poor acceleration", "Failed smog test"], causes: ["Faulty catalytic converter on Bank 2", "Failed downstream O2 sensor", "Intake leak", "Exhaust leak on Bank 2"], severity: "Medium" },
  { code: "P0174", title: "System Too Lean (Bank 2)", description: "Bank 2 is running excessively lean (too much air, not enough fuel).", symptoms: ["Check Engine Light ON", "Rough idle", "Engine hesitation", "Decreased power"], causes: ["Vacuum leak near Bank 2", "Dirty MAF sensor", "Clogged fuel injectors on Bank 2", "Exhaust leak upstream of O2 sensor"], severity: "Medium" },
  { code: "P0442", title: "Evaporative Emission System Leak Detected (Small Leak)", description: "The ECM has detected a very small leak in the EVAP system.", symptoms: ["Check Engine Light ON", "Slight fuel odor"], causes: ["Loose fuel cap", "Small crack in EVAP hose", "Faulty vent solenoid", "Faulty EVAP purge valve"], severity: "Low" },
  { code: "P0456", title: "Evaporative Emission System Leak Detected (Very Small Leak)", description: "The ECM has detected an incredibly small fuel vapor leak in the EVAP system.", symptoms: ["Check Engine Light ON"], causes: ["Worn fuel cap seal", "Pin-hole leak in an EVAP hose", "Defective purge or vent valve"], severity: "Low" },
  { code: "P0128", title: "Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)", description: "The engine is taking too long to reach its optimal operating temperature.", symptoms: ["Check Engine Light ON", "Heater not blowing hot air", "Engine temperature gauge reading low", "Poor fuel economy"], causes: ["Stuck open thermostat", "Low engine coolant level", "Faulty coolant temperature sensor", "Faulty radiator fan switch"], severity: "Medium" },
  { code: "P0301", title: "Cylinder 1 Misfire Detected", description: "The ECM has detected that Cylinder 1 is misfiring.", symptoms: ["Check Engine Light flashing", "Engine trembling", "Lack of power", "Strong exhaust smell"], causes: ["Faulty spark plug on Cyl 1", "Defective ignition coil on Cyl 1", "Clogged fuel injector on Cyl 1", "Low compression on Cyl 1"], severity: "High" },
  { code: "P0302", title: "Cylinder 2 Misfire Detected", description: "The ECM has detected a misfire in Cylinder 2.", symptoms: ["Check Engine Light flashing", "Rough idle", "Engine misfire on load"], causes: ["Bad spark plug on Cyl 2", "Failed coil pack on Cyl 2", "Faulty fuel injector", "Vacuum leak"], severity: "High" },
  { code: "P0303", title: "Cylinder 3 Misfire Detected", description: "The ECM has detected a misfire in Cylinder 3.", symptoms: ["Check Engine Light flashing", "Stumbling acceleration", "Decreased fuel economy"], causes: ["Worn spark plug Cyl 3", "Bad ignition coil", "Intake manifold leak", "Low fuel pressure"], severity: "High" },
  { code: "P0304", title: "Cylinder 4 Misfire Detected", description: "The ECM has detected a misfire in Cylinder 4.", symptoms: ["Check Engine Light flashing", "Engine vibration", "Raw fuel smell from exhaust"], causes: ["Faulty coil pack Cyl 4", "Fouled spark plug", "Burnt exhaust valve", "Leaking head gasket"], severity: "High" },
  { code: "P0325", title: "Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)", description: "The ECM is not receiving an operational signal from the knock sensor.", symptoms: ["Check Engine Light ON", "Engine pinging or knocking", "Sluggish acceleration"], causes: ["Defective knock sensor", "Knock sensor wiring harness shorted or open", "Poor connection at the knock sensor", "Engine mechanically noisy"], severity: "Medium" },
  { code: "P0500", title: "Vehicle Speed Sensor 'A' Malfunction", description: "The ECM is not receiving a valid speed signal from the Vehicle Speed Sensor (VSS).", symptoms: ["Check Engine Light ON", "Speedometer not working", "Anti-lock brakes (ABS) light ON", "Transmission shifting harshly"], causes: ["Failed Vehicle Speed Sensor", "Broken VSS wiring", "Damaged instrument cluster", "Faulty ECM"], severity: "Medium" },
  { code: "P0700", title: "Transmission Control System Malfunction", description: "A generic trouble code indicating the Transmission Control Module (TCM) has detected a transmission fault.", symptoms: ["Check Engine Light ON", "Transmission slipping", "Harsh shifting", "Vehicle stuck in Limp Mode"], causes: ["TCM failure", "Low transmission fluid", "Defective shift solenoids", "Transmission wiring damage"], severity: "Critical" },
  { code: "P0740", title: "Torque Converter Clutch Circuit Malfunction", description: "The ECM detects a fault in the torque converter clutch (TCC) circuit.", symptoms: ["Check Engine Light ON", "Decreased fuel economy on highway", "Engine RPM higher than normal at cruising speed"], causes: ["Failed TCC solenoid", "Dirty transmission fluid", "TCC control circuit wiring issue", "Internal transmission failure"], severity: "High" },
  { code: "P0101", title: "Mass or Volume Air Flow Circuit Range/Performance Problem", description: "The Mass Air Flow (MAF) sensor signal to the ECM is out of the expected range.", symptoms: ["Check Engine Light ON", "Rough idle", "Engine surging", "Stalling right after starting"], causes: ["Dirty or contaminated MAF sensor", "Vacuum leak", "Clogged air filter", "Faulty MAF circuit wiring"], severity: "Medium" },
  { code: "P0102", title: "Mass or Volume Air Flow Circuit Low Input", description: "The Mass Air Flow (MAF) sensor output is lower than expected.", symptoms: ["Check Engine Light ON", "Engine stalling", "Lack of power", "Black smoke from exhaust"], causes: ["Failed MAF sensor", "Large vacuum leak", "Clogged catalytic converter", "Electrical short to ground in MAF circuit"], severity: "Medium" },
  { code: "P0118", title: "Engine Coolant Temperature Circuit High Input", description: "The ECM interprets a high voltage signal from the ECT sensor as a temperature of -40°F (indicating an open circuit).", symptoms: ["Check Engine Light ON", "Hard starting when cold", "Poor fuel economy", "Radiator fans run constantly"], causes: ["Unplugged Engine Coolant Temperature (ECT) sensor", "Broken ECT wiring", "Failed ECT sensor"], severity: "Medium" },
  { code: "P0122", title: "Throttle Pedal Position Sensor/Switch A Circuit Low Input", description: "The ECM detects that the TPS voltage signal is excessively low.", symptoms: ["Check Engine Light ON", "Hesitation upon acceleration", "Vehicle stalling", "Irregular shifting"], causes: ["Defective Throttle Position Sensor (TPS)", "Short circuit in TPS wiring", "Improperly adjusted TPS", "Faulty ECM"], severity: "High" },
  { code: "P0400", title: "Exhaust Gas Recirculation Flow Malfunction", description: "The ECM detects an incorrect amount of EGR flow.", symptoms: ["Check Engine Light ON", "Engine pinging under load", "Failed emissions testing"], causes: ["Clogged EGR passages", "Faulty EGR Valve", "Vacuum supply issue to the EGR valve"], severity: "Medium" },
  { code: "P0440", title: "Evaporative Emission Control System Malfunction", description: "The ECM has detected a malfunction in the EVAP system, meaning vapor is not being properly contained.", symptoms: ["Check Engine Light ON", "Visible or noticeable fuel smell"], causes: ["Missing or loose gas cap", "Faulty EVAP purge solenoid", "Leaking charcoal canister", "Broken EVAP line"], severity: "Low" },
  { code: "P0446", title: "Evaporative Emission Control System Vent Control Circuit Malfunction", description: "The ECM detects an electrical issue with the EVAP vent valve circuit.", symptoms: ["Check Engine Light ON"], causes: ["Failed EVAP vent valve", "Short or open in vent valve wiring", "Blocked EVAP vent filter"], severity: "Medium" },
  { code: "P0505", title: "Idle Control System Malfunction", description: "The ECM is unable to control the engine idle speed properly.", symptoms: ["Check Engine Light ON", "Unusually high or low idle", "Engine stalling at stops", "Fluctuating idle RPM"], causes: ["Carbon buildup in Idle Air Control (IAC) valve", "Vacuum leak", "Failed IAC valve", "Clogged throttle body"], severity: "Medium" },
  { code: "P0720", title: "Output Speed Sensor Circuit Malfunction", description: "The ECM/TCM is not receiving a functional signal from the Output Speed Sensor (OSS).", symptoms: ["Check Engine Light ON", "Speedometer malfunction", "Harsh shifting", "Erratic transmission behavior"], causes: ["Defective Output Speed Sensor", "Corroded OSS connector", "Damaged OSS wiring", "Faulty TCM"], severity: "Medium" },
  { code: "P0730", title: "Incorrect Gear Ratio", description: "The ECM has determined that the transmission is not shifting properly and has an incorrect gear ratio.", symptoms: ["Check Engine Light ON", "Transmission slipping", "Delayed engagement", "Loss of specific gears"], causes: ["Low or dirty transmission fluid", "Failed shift solenoids", "Internal mechanical transmission failure", "Torque converter failure"], severity: "Critical" },
  { code: "P0155", title: "O2 Sensor Heater Circuit (Bank 2 Sensor 1)", description: "The ECM detects a malfunction in the Bank 2 Sensor 1 oxygen sensor heater circuit.", symptoms: ["Check Engine Light ON", "Poor fuel economy", "Failed emissions test"], causes: ["Failed oxygen sensor heater element", "Blown O2 heater fuse", "Broken O2 sensor wiring", "Poor electrical connection"], severity: "Medium" },
  { code: "P0133", title: "Oxygen Sensor Circuit Slow Response (Bank 1 Sensor 1)", description: "The ECM detects that the upstream O2 sensor is responding too slowly to changes in the air/fuel mixture.", symptoms: ["Check Engine Light ON", "Higher fuel consumption", "Hesitation upon acceleration"], causes: ["Aged or contaminated O2 sensor", "Exhaust leak near the sensor", "Rich or lean running condition", "MAF sensor issue"], severity: "Medium" },
  { code: "P0201", title: "Injector Circuit Malfunction - Cylinder 1", description: "The ECM detects an electrical malfunction in the fuel injector circuit for Cylinder 1.", symptoms: ["Check Engine Light ON", "Engine misfire", "Rough idle", "Loss of power"], causes: ["Failed fuel injector on Cylinder 1", "Broken wiring to the injector", "Poor connection at the injector harness", "Faulty ECM"], severity: "High" },
  { code: "P0011", title: "A Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)", description: "The ECM has determined the camshaft timing is more advanced than it commanded.", symptoms: ["Check Engine Light ON", "Rough idle", "Engine stalling", "Rattling noise from upper engine"], causes: ["Low engine oil level", "Dirty or contaminated engine oil", "Failed Variable Valve Timing (VVT) solenoid", "Worn timing chain guides"], severity: "High" },
  { code: "P0014", title: "B Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)", description: "The exhaust camshaft timing on Bank 1 is exceeding the commanded parameters.", symptoms: ["Check Engine Light ON", "Poor engine performance", "Rough idle", "Rattling noise from engine"], causes: ["Low oil level", "Dirty engine oil", "Failed VVT exhaust solenoid", "Mechanical timing failure"], severity: "High" },
  { code: "P0121", title: "Throttle/Pedal Position Sensor A Circuit Range/Performance", description: "The TPS sensor is producing a signal that does not match the expected range based on engine conditions.", symptoms: ["Check Engine Light ON", "Hesitation on acceleration", "Vehicle stuck in 'Limp Mode'", "Irregular idle"], causes: ["Faulty Throttle Position Sensor", "Dirty throttle body", "Damaged TPS wiring harness", "Corroded connector"], severity: "Medium" },
  { code: "P0130", title: "O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)", description: "The ECM has detected a malfunction with the primary oxygen sensor circuit on Bank 1.", symptoms: ["Check Engine Light ON", "Excessive fuel consumption", "Rough running condition"], causes: ["Defective O2 Sensor", "Exhaust leak", "Short to ground in O2 sensor wiring", "Rich or Lean operating condition"], severity: "Medium" },
  { code: "P0150", title: "O2 Sensor Circuit Malfunction (Bank 2 Sensor 1)", description: "The ECM detects a general fault in the upstream O2 sensor on Bank 2.", symptoms: ["Check Engine Light ON", "Decreased fuel efficiency", "Rich fuel smell"], causes: ["Failed Bank 2 O2 sensor", "Vacuum leak on Bank 2", "Damaged O2 wiring", "Exhaust manifold leak"], severity: "Medium" },
  { code: "P0299", title: "Turbocharger/Supercharger Underboost", description: "The ECM detects that the turbocharger or supercharger is not generating the required amount of boost pressure.", symptoms: ["Check Engine Light ON", "Severe lack of engine power", "Whining or hissing noise from engine bay", "Vehicle in Limp Mode"], causes: ["Boost leak in intake piping", "Failed turbocharger wastegate", "Damaged turbocharger impeller", "Faulty boost pressure sensor"], severity: "Critical" },
  { code: "P2181", title: "Cooling System Performance", description: "The ECM has detected that the engine cooling system is not operating within nominal temperature parameters.", symptoms: ["Check Engine Light ON", "Temperature gauge sits too high or too low", "Heater blows cold air", "Coolant boiling"], causes: ["Failed thermostat", "Faulty Coolant Temperature Sensor", "Low coolant level", "Failed water pump"], severity: "High" },
  { code: "C0040", title: "Right Front Wheel Speed Sensor Malfunction (Chassis Code)", description: "The ABS control module is not receiving a valid speed signal from the right front wheel speed sensor.", symptoms: ["ABS Light ON", "Traction Control Light ON", "Speedometer erratic", "ABS engages randomly"], causes: ["Failed right front wheel speed sensor", "Damaged sensor wiring harness", "Dirty or damaged reluctor ring", "Faulty ABS module"], severity: "High" },
  { code: "U0100", title: "Lost Communication with ECM/PCM A (Network Code)", description: "Other modules on the CAN bus network cannot communicate with the Engine Control Module.", symptoms: ["Check Engine Light ON", "Vehicle will not start", "Multiple warning lights on dash", "Transmission won't shift"], causes: ["Dead or weak battery", "Corroded ECM ground connections", "Blown ECM power fuse", "Failed ECM"], severity: "Critical" },
  { code: "P2004", title: "Intake Manifold Runner Control Stuck Open Bank 1", description: "The ECM detects that the intake manifold runner control flaps are stuck in the open position.", symptoms: ["Check Engine Light ON", "Hesitation at low RPMs", "Poor low-end torque"], causes: ["Broken IMRC actuator mechanism", "Carbon buildup holding flaps open", "Vacuum leak to the IMRC actuator", "Failed IMRC solenoid"], severity: "Medium" },
  { code: "P2138", title: "Throttle/Pedal Position Sensor/Switch D/E Voltage Correlation", description: "The ECM detects that the two voltage signals from the accelerator pedal position sensor do not correlate.", symptoms: ["Check Engine Light ON", "Vehicle stuck in Limp Mode (no acceleration)", "Engine stalls"], causes: ["Failed accelerator pedal position (APP) sensor", "Corroded APP wiring connector", "Short circuit in APP wiring", "Failed electronic throttle body"], severity: "Critical" },
  { code: "P2293", title: "Fuel Pressure Regulator 2 Performance", description: "The ECM detects a discrepancy between the target high-pressure fuel rail pressure and the actual measured pressure.", symptoms: ["Check Engine Light ON", "Sudden loss of power on acceleration", "Vehicle stalling", "Hard starting"], causes: ["Failed high-pressure fuel pump (HPFP)", "Worn camshaft lobe driving the HPFP", "Clogged fuel filter", "Failed fuel rail pressure sensor"], severity: "High" },
  { code: "P0087", title: "Fuel Rail/System Pressure - Too Low", description: "The ECM detects that the fuel pressure in the high-pressure fuel rail is lower than commanded.", symptoms: ["Check Engine Light ON", "Engine misfires under heavy load", "Engine stalling", "Limp Mode engaged"], causes: ["Failing High-Pressure Fuel Pump", "Clogged in-tank fuel filter", "Failing low-pressure lift pump", "Leaky fuel injector"], severity: "High" },
  { code: "P0741", title: "Torque Converter Clutch Circuit Performance or Stuck Off", description: "The ECM commands the torque converter clutch to engage, but the input/output speeds indicate it is not locking up.", symptoms: ["Check Engine Light ON", "Higher RPMs at highway speeds", "Decreased fuel economy", "Slight shudder at cruising speed"], causes: ["Mechanical failure of the Torque Converter", "Worn Torque Converter Clutch Solenoid", "Low transmission fluid pressure", "Internal transmission seals leaking"], severity: "High" },
  { code: "P0016", title: "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)", description: "The ECM detects that the timing between the crankshaft and the intake camshaft on Bank 1 is out of sync.", symptoms: ["Check Engine Light ON", "Rough idle", "Engine crank but no start", "Rattling noise from timing cover"], causes: ["Stretched timing chain", "Skipped timing belt tooth", "Failed Variable Valve Timing actuator", "Failed cam or crank sensor"], severity: "Critical" },
  { code: "P0A0F", title: "Engine Failed to Start (Hybrid Code)", description: "The Hybrid Vehicle Control Module attempted to start the internal combustion engine but failed.", symptoms: ["Check Engine Light ON", "Red Triangle 'Master Warning' ON", "Vehicle will only drive on battery power until dead"], causes: ["Empty gas tank", "Clogged fuel injectors", "Failed throttle body", "Faulty Mass Air Flow Sensor"], severity: "Critical" }
];

export function getDtcByCode(code: string): DTCData | undefined {
  return TOP_DTC_CODES.find(d => d.code.toUpperCase() === code.toUpperCase());
}
