import { Layout } from "@/components/Layout";
import { SEO } from "@/components/SEO";

const glossaryTerms = [
  { term: "DTC (Diagnostic Trouble Code)", def: "An alphanumeric code generated by a vehicle's On-Board Diagnostics (OBD) system when it detects a malfunction. Codes are categorized as P (Powertrain), B (Body), C (Chassis), and U (Network)." },
  { term: "OBD2 (On-Board Diagnostics II)", def: "A standardized system mandated in vehicles (US from 1996, EU from 2001/2004) that provides near real-time data and access to diagnostic information and standardized DTCs." },
  { term: "OEM (Original Equipment Manufacturer)", def: "The original manufacturer of a vehicle or its components. OEM repair data refers to the exact, unedited service manuals, wiring diagrams, and diagnostic flowcharts published by the vehicle manufacturer." },
  { term: "TSB (Technical Service Bulletin)", def: "An official notification issued by a vehicle manufacturer regarding a known common problem and providing the recommended repair procedure to dealership technicians." },
  { term: "ECU (Electronic Control Unit)", def: "Any embedded system in automotive electronics that controls one or more of the electrical systems or subsystems in a vehicle (e.g., Engine Control Module, Brake Control Module)." },
  { term: "PCM (Powertrain Control Module)", def: "A combined control unit, consisting of the Engine Control Unit (ECU) and the Transmission Control Unit (TCU), managing the power delivery of the vehicle." },
  { term: "CAN Bus (Controller Area Network)", def: "A robust vehicle bus standard designed to allow microcontrollers and devices to communicate with each other's applications without a host computer." },
  { term: "Freeze Frame Data", def: "A snapshot of engine and sensor data recorded by the vehicle's computer the exact moment a Diagnostic Trouble Code (DTC) was registered, crucial for intermittent fault diagnosis." },
  { term: "Live Data PIDs", def: "Parameter Identification (PID) codes used to request data in real-time from a vehicle's data stream, allowing technicians to verify if a sensor or component is functioning correctly." },
  { term: "VESA (Vehicle Electronics Smart Assistant)", def: "An interactive, intelligent wiring diagram system (notably associated with Haynes Pro) that guides technicians through logical fault-finding steps on CAN Bus and electrical systems." }
];

export default function Glossary() {
  const glossarySchema = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "DefinedTermSet",
    "name": "Automotive Diagnostic and Workshop Glossary",
    "description": "Definitions for common automotive diagnostic, repair, and electronics terminology used by professional mechanics.",
    "hasDefinedTerm": glossaryTerms.map(t => ({
      "@type": "DefinedTerm",
      "name": t.term,
      "description": t.def
    }))
  });

  return (
    <Layout>
      <SEO 
        title="Automotive Diagnostic Glossary & Terminology | Auto Fix Data"
        description="A professional A-Z glossary covering DTCs, OBD2, OEM metrics, TSBs, and CAN bus systems. Learn the exact definitions used by master technicians."
        schema={glossarySchema}
      />
      
      <section className="bg-afd-navy py-20 px-6 dark-section border-b border-white/10">
        <div className="max-w-[800px] mx-auto text-center">
          <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-6">Automotive Diagnostic Glossary</h1>
          <p className="text-xl text-afd-slate leading-relaxed">
            Clear, technical definitions for the advanced diagnostic terminology, components, and systems found in the Auto Fix Data platform.
          </p>
        </div>
      </section>

      <section className="py-20 px-6 bg-white">
        <div className="max-w-[1000px] mx-auto">
          <div className="bg-afd-light border border-gray-100 p-8 rounded-2xl shadow-sm">
            <dl className="space-y-8">
              {glossaryTerms.sort((a,b) => a.term.localeCompare(b.term)).map(({ term, def }) => (
                <div key={term} className="border-b border-gray-200 pb-8 last:border-0 last:pb-0">
                  <dt className="text-2xl font-bold text-afd-navy mb-3"><dfn>{term}</dfn></dt>
                  <dd className="text-afd-text text-lg leading-relaxed">{def}</dd>
                </div>
              ))}
            </dl>
          </div>
        </div>
      </section>
    </Layout>
  );
}
